import assert from "node:assert/strict";
import test from "node:test";
import { accessibilityTags, bodyPositions, equipment, exerciseTypes, movementPatterns, muscles, trackingTemplates } from "../src/exerciseDatabase/taxonomies.ts";
import { canonicalExerciseDatabase, validateTaxonomies } from "../src/exerciseDatabase/validation.ts";
import { reviewedExercises } from "../src/exerciseDatabase/reviewedExercises.ts";
import { getMuscleChildren, getMuscleDescendants, isTrackingUnitSupported, searchEquipment } from "../src/exerciseDatabase/search.ts";

const database=canonicalExerciseDatabase(reviewedExercises);
test("all normalized taxonomies pass integrity validation",()=>assert.deepEqual(validateTaxonomies(database),[]));
test("muscle parents expose broad and precise hologram targets",()=>{ const chestChildren=getMuscleChildren(muscles,"pectoralis_major").map((x)=>x.id); assert.deepEqual(chestChildren.sort(),["pectoralis_major_clavicular","pectoralis_major_costal","pectoralis_major_sternal"]); assert.ok(getMuscleDescendants(muscles,"hips_glutes").some((x)=>x.id==="psoas_major")); assert.ok(muscles.every((x)=>x.visualSvgTargetId.startsWith("muscle-")&&x.visibility.length&&x.laterality.length)); });
test("equipment aliases and suitability are searchable",()=>{ assert.equal(searchEquipment(equipment,"DB")[0].id,"dumbbell"); assert.equal(searchEquipment(equipment,"exercise bike")[0].id,"stationary_bike"); assert.ok(equipment.every((x)=>x.suitability.length&&x.equipmentGroup&&x.resistanceType)); });
test("movement, type, position and accessibility vocabularies include required reference values",()=>{ for(const id of ["horizontal_push","hinge","anti_rotation","change_of_direction"])assert.ok(movementPatterns.some((x)=>x.id===id)); for(const id of ["strength","cardiovascular","rehabilitation","breathing"])assert.ok(exerciseTypes.includes(id)); for(const id of ["side_lying","quadruped","single_leg"])assert.ok(bodyPositions.includes(id)); for(const id of ["wheelchair_compatible","reduced_spinal_loading","return_to_training"])assert.ok(accessibilityTags.includes(id)); });
test("all 21 tracking templates declare coherent fields and capabilities",()=>{ assert.equal(trackingTemplates.length,21); for(const template of trackingTemplates){assert.deepEqual(new Set(template.fields.map((x)=>x.id)),new Set([...template.requiredFieldIds,...template.optionalFieldIds]));assert.ok(template.fields.every((x)=>template.supportedUnits.includes(x.defaultUnit)));} assert.equal(trackingTemplates.find((x)=>x.id==="cardio_intervals").supportsIntervals,true); assert.equal(trackingTemplates.find((x)=>x.id==="timed_hold").supportsAddedWeight,true); });
test("tracking unit compatibility is field-specific",()=>{ assert.equal(isTrackingUnitSupported(database,"reps_and_weight","weight","kg"),true); assert.equal(isTrackingUnitSupported(database,"reps_and_weight","weight","bpm"),false); assert.equal(isTrackingUnitSupported(database,"cardio_session","heart_rate","bpm"),true); });
