import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs";
import { anatomyPaths, parentVisualChildren, resolveVisualActivation, visualPathIds } from "../src/components/anatomyVisualMap.ts";
import { normalizeExerciseKey, productionExerciseLibrary } from "../src/exerciseDatabase/libraryExercises.ts";

const activationFor=(name)=>{const exercise=productionExerciseLibrary.find((item)=>[item.displayName,item.canonicalName,...item.aliases].some((value)=>normalizeExerciseKey(value)===normalizeExerciseKey(name)));assert.ok(exercise,`Missing test exercise ${name}`);return Object.fromEntries(exercise.muscles.map((item)=>[item.muscleId,{role:item.role==="dynamic_stabilizer"?"stabilizer":item.role==="stabilizer"?"stabilizer":item.role==="synergist"?"synergist":item.role==="primary"?"primary":item.role==="secondary"?"secondary":"supporting",contribution:item.contributionLevel}]));};
test("front and rear use canonical permanent muscle IDs",()=>{assert.ok(anatomyPaths.some((item)=>item.side==="front"));assert.ok(anatomyPaths.some((item)=>item.side==="back"));assert.equal(new Set(anatomyPaths.map((item)=>`${item.side}:${item.id}`)).size,anatomyPaths.length);for(const item of anatomyPaths)assert.match(item.id,/^[a-z0-9]+(?:_[a-z0-9]+)*$/);});
test("parent muscle activation expands into detailed SVG children",()=>{const resolved=resolveVisualActivation({quadriceps:{role:"primary",contribution:"high"}});for(const id of parentVisualChildren.quadriceps.filter((item)=>visualPathIds.has(item)))assert.equal(resolved[id].role,"primary");});
test("unknown visual mappings fail cleanly and report the missing ID",()=>{const missing=[];assert.deepEqual(resolveVisualActivation({not_a_real_muscle:{role:"primary",contribution:"high"}},(id)=>missing.push(id)),{});assert.deepEqual(missing,["not_a_real_muscle"]);});
test("different exercise families resolve without crashing",()=>{for(const name of ["Dumbbell Bench Press","Barbell Back Squat","Barbell Romanian Deadlift","Pull-Up","Push-Up Isometric Hold","Cable Pallof Press","Dumbbell Lateral Raise","Farmer Carry","Stationary Bike","Hip Flexor Stretch"]){const resolved=resolveVisualActivation(activationFor(name));assert.ok(Object.keys(resolved).length,`${name} has no rendered activation`);}});
test("roles remain distinct through resolution",()=>{const resolved=resolveVisualActivation({pectoralis_major:{role:"primary",contribution:"high"},anterior_deltoid:{role:"secondary",contribution:"moderate"},serratus_anterior:{role:"stabilizer",contribution:"low"}});assert.ok(Object.values(resolved).some((item)=>item.role==="primary"));assert.ok(Object.values(resolved).some((item)=>item.role==="secondary"));});
test("component source includes keyboard, screen reader and synchronized interaction contracts",()=>{const source=fs.readFileSync(new URL("../src/components/AnatomyMap.tsx",import.meta.url),"utf8");for(const marker of ["aria-label","aria-live","tabIndex","onKeyDown","onMouseEnter","onFocus","aria-pressed","data-muscle-id"])assert.ok(source.includes(marker),marker);});
test("CSS provides mobile, dark-token, high contrast and reduced-motion behaviour",()=>{const source=fs.readFileSync(new URL("../src/components/AnatomyMap.css",import.meta.url),"utf8");for(const marker of ["@media(max-width:520px)","prefers-reduced-motion:reduce","data-high-contrast","var(--blue)","role-primary","role-secondary","role-supporting","role-stabilizer"])assert.ok(source.includes(marker),marker);});
