import assert from "node:assert/strict";
import test from "node:test";
import { productionExerciseLibrary } from "../src/exerciseDatabase/libraryExercises.ts";
import { trackingTemplates } from "../src/exerciseDatabase/taxonomies.ts";
import { calculateExerciseProgress, createTrackingSet, defaultUnitPreferences, fromCanonical, legacyCompatibleSet, summarizeTrackingSet, swapReasons, toCanonical } from "../src/exerciseDatabase/trackingEngine.ts";

const exercise=(predicate)=>{const found=productionExerciseLibrary.find(predicate);assert.ok(found);return found;};
const template=(id)=>{const found=trackingTemplates.find((item)=>item.id===id);assert.ok(found);return found;};

test("every tracking template creates a serializable compatible set",()=>{for(const item of productionExerciseLibrary){const set=createTrackingSet(item,template(item.trackingTemplateId));assert.equal(set.complete,false);assert.ok(set.values);assert.ok(set.units);assert.equal(legacyCompatibleSet(set).setKind,"working");}});
test("legacy weight and reps are upgraded without being removed",()=>{const set=legacyCompatibleSet({weight:"50",reps:"12",complete:true});assert.equal(set.weight,"50");assert.equal(set.reps,"12");assert.equal(set.values.weight,"50");assert.equal(set.values.reps,"12");});
test("weight, distance, pace, and speed conversion round trips",()=>{const kg=toCanonical(220.462262,"lb");assert.ok(Math.abs(kg.value-100)<.001);assert.ok(Math.abs(fromCanonical(kg.value,"kg","lb")-220.462262)<.001);const metres=toCanonical(1,"miles");assert.equal(metres.value,1609.344);assert.ok(Math.abs(fromCanonical(metres.value,"metres","yards")-1760)<.001);assert.ok(Math.abs(toCanonical(5280,"feet").value-1609.344)<.001);assert.ok(Math.abs(toCanonical(1760,"yards").value-1609.344)<.001);const pace=toCanonical(8,"min_per_mile");assert.ok(Math.abs(fromCanonical(pace.value,pace.unit,"min_per_mile")-8)<.001);const speed=toCanonical(10,"miles_per_hour");assert.ok(Math.abs(fromCanonical(speed.value,speed.unit,"miles_per_hour")-10)<.001);});
test("history summaries use the exercise tracking style",()=>{const prefs=defaultUnitPreferences(false);const hold=exercise((item)=>item.trackingTemplateId==="timed_hold");assert.match(summarizeTrackingSet(hold,{complete:true,values:{duration:20,position:"top"},units:{duration:"seconds"}},prefs),/20s top/);const carry=exercise((item)=>item.trackingTemplateId==="loaded_carry");assert.match(summarizeTrackingSet(carry,{weight:"70",complete:true,values:{weight:70,distance:40},units:{weight:"lb",distance:"metres"},weightMeaning:"per_implement"},prefs),/40 metres carry.*70 lb per hand/);const rope=exercise((item)=>item.trackingTemplateId==="jump_rope");assert.match(summarizeTrackingSet(rope,{complete:true,values:{rounds:3,steps:60}},prefs),/3 rounds.*60 skips/);});
test("progress metrics never apply 1RM to cardio or holds",()=>{const cardio=exercise((item)=>item.cardio);const cardioProgress=calculateExerciseProgress(cardio,[{complete:true,values:{duration:1800,distance:5.2,pace:346,heart_rate:142,watts:190}}]);assert.equal(cardioProgress.kind,"cardio");assert.equal(cardioProgress.longestDistance,5.2);const hold=exercise((item)=>item.timedHold);const holdProgress=calculateExerciseProgress(hold,[{complete:true,values:{duration:20,added_weight:10}},{complete:true,values:{duration:30}}]);assert.equal(holdProgress.kind,"timed_hold");assert.equal(holdProgress.longestHold,30);assert.equal(holdProgress.totalHold,50);});
test("missing cardio pace is finite and multi-position holds total every position",()=>{const cardio=exercise((item)=>item.cardio);assert.equal(calculateExerciseProgress(cardio,[{complete:true,values:{duration:600}}]).fastestPace,0);const hold=exercise((item)=>item.trackingTemplateId==="multi_position_timed_hold");const set={complete:true,values:{top_duration:10,midpoint_duration:8,bottom_duration:7}};assert.match(summarizeTrackingSet(hold,set,defaultUnitPreferences(true)),/25s/);const progress=calculateExerciseProgress(hold,[set]);assert.equal(progress.longestHold,25);assert.equal(progress.totalHold,25);});
test("unilateral progress reports side imbalance",()=>{const unilateral=exercise((item)=>item.unilateral);const progress=calculateExerciseProgress(unilateral,[{complete:true,values:{reps_left:10,reps_right:8}}]);assert.equal(progress.kind,"unilateral");assert.equal(progress.imbalancePercent,20);});
test("swap suggestions expose useful reasons",()=>{const from=exercise((item)=>item.id==="dumbbell_bench_press");const candidate=productionExerciseLibrary.map((item)=>({item,reasons:swapReasons(from,item)})).find(({item,reasons})=>item.id!==from.id&&reasons.includes("same primary muscles")&&reasons.includes("same movement pattern"));assert.ok(candidate);});
