import { exerciseLibrary as legacyExercises, type ExerciseDefinition } from "../data/exercises";
import { getExerciseGuidance } from "../data/exerciseGuidance";
import { getMuscleActivation } from "../data/muscleActivations";
import { catalogueAdditions, type CatalogueAddition } from "./catalogueAdditions";
import { muscles, trackingTemplates } from "./taxonomies";
import { reviewedExercises } from "./reviewedExercises";
import type { Difficulty, Exercise, ExerciseMuscle, ExerciseRelationship, ExerciseType } from "./types";

const NOW="2026-07-17T00:00:00.000Z";
export const normalizeExerciseKey=(value:string)=>value.toLocaleLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();
const slug=(value:string)=>normalizeExerciseKey(value).replaceAll(" ","_");
const muscleIdMap:Record<string,string>={chest:"pectoralis_major",triceps:"triceps_brachii","front-delts":"anterior_deltoid","side-delts":"lateral_deltoid","rear-delts":"posterior_deltoid",lats:"latissimus_dorsi",traps:"trapezius_middle",biceps:"biceps_brachii",forearms:"forearm_flexors",abs:"rectus_abdominis",obliques:"external_obliques","lower-back":"erector_spinae",glutes:"gluteus_maximus",quads:"quadriceps",adductors:"hip_adductors",hamstrings:"hamstrings",calves:"gastrocnemius",tibialis:"tibialis_anterior"};

const machineEquipment=(name:string)=>{const n=normalizeExerciseKey(name);const matches:Array<[RegExp,string]>=[[/incline.*chest press/,"incline_chest_press_machine"],[/chest press/,"chest_press_machine"],[/pec|chest fly/,"pec_deck"],[/reverse fly|reverse pec/,"reverse_pec_deck"],[/shoulder press/,"shoulder_press_machine"],[/lateral raise/,"lateral_raise_machine"],[/lat pulldown/,"lat_pulldown_machine"],[/high row/,"high_row_machine"],[/low row/,"low_row_machine"],[/row/,"seated_row_machine"],[/assisted pull|assisted dip/,"assisted_pull_up_dip_machine"],[/leg press/,"leg_press_machine"],[/hack squat/,"hack_squat_machine"],[/pendulum/,"pendulum_squat_machine"],[/belt squat/,"belt_squat_machine"],[/leg extension/,"leg_extension_machine"],[/seated leg curl/,"seated_leg_curl_machine"],[/lying leg curl/,"lying_leg_curl_machine"],[/standing leg curl/,"standing_leg_curl_machine"],[/hip thrust/,"hip_thrust_machine"],[/glute drive/,"glute_drive_machine"],[/hip abduction/,"hip_abductor_machine"],[/hip adduction/,"hip_adductor_machine"],[/calf raise/,"calf_raise_machine"],[/rotary torso/,"rotary_torso_machine"],[/abdominal crunch/,"abdominal_crunch_machine"],[/back extension/,"back_extension_machine"],[/preacher curl/,"preacher_curl_machine"],[/biceps curl/,"biceps_curl_machine"],[/triceps extension/,"triceps_extension_machine"],[/dip/,"dip_machine"]];return matches.find(([pattern])=>pattern.test(n))?.[1]??"functional_trainer";};
const cardioEquipment=(name:string)=>{const n=normalizeExerciseKey(name);const matches:Array<[RegExp,string]>=[[/manual treadmill/,"manual_treadmill"],[/treadmill/,"treadmill"],[/spin/,"spin_bike"],[/recumbent/,"recumbent_bike"],[/air bike/,"air_bike"],[/bike|cycling/,"stationary_bike"],[/rowing/,"rowing_machine"],[/ski/,"ski_erg"],[/elliptical/,"elliptical"],[/stair climber/,"stair_climber"],[/step mill|stepmill/,"step_mill"],[/arc trainer/,"arc_trainer"],[/versaclimber/,"versaclimber"],[/jump rope/,"jump_rope"]];return matches.find(([pattern])=>pattern.test(n))?.[1]??"bodyweight";};
const conditioningEquipment=(name:string)=>{const n=normalizeExerciseKey(name);if(n.includes("battle rope"))return"battle_ropes";if(n.includes("sled"))return"sled";if(n.includes("tire"))return"tire";if(n.includes("sledgehammer"))return"sledgehammer";if(n.includes("agility ladder"))return"agility_ladder";if(n.includes("medicine ball"))return"medicine_ball";if(n.includes("sandbag"))return"sandbag";if(n.includes("box jump"))return"plyometric_box";return"bodyweight";};
function resolveEquipment(source:string,name:string):string { const direct:Record<string,string>={Bodyweight:"bodyweight",None:"bodyweight",Dumbbell:"dumbbell",Barbell:"barbell","EZ bar":"ez_curl_bar",Kettlebell:"kettlebell",Bench:"flat_bench",Cable:"cable_stack","Resistance band":"long_resistance_band","Smith machine":"smith_machine",Landmine:"barbell",Bike:"stationary_bike","Pull-up bar":"pull_up_bar",Sled:"sled","Medicine ball":"medicine_ball",Treadmill:"treadmill","Foam roller":"foam_roller",Rings:"gymnastics_rings","Dip station":"dip_bars","Stability ball":"stability_ball","Plyo box":"plyometric_box","Battle rope":"battle_ropes","Stair machine":"stair_climber",Sandbag:"sandbag",Plate:"weight_plate",Slider:"floor","Ab wheel":"bodyweight","Air bike":"air_bike",Rower:"rowing_machine","Ski erg":"ski_erg",Elliptical:"elliptical","Jump rope":"jump_rope",pull_up_bar:"pull_up_bar",bodyweight:"bodyweight",dumbbell:"dumbbell",barbell:"barbell",kettlebell:"kettlebell",long_resistance_band:"long_resistance_band",mini_band:"mini_band",cable_stack:"cable_stack"}; if(/machine-assisted/.test(name.toLocaleLowerCase()))return"assisted_pull_up_dip_machine";if(/band-assisted/.test(name.toLocaleLowerCase()))return"assisted_pull_up_band";if(source==="machine"||source==="Machine")return machineEquipment(name);if(source==="cardio")return cardioEquipment(name);if(source==="conditioning")return conditioningEquipment(name);return direct[source]??source; }

function categoryId(category:string){if(["Chest","Back","Shoulders","Biceps","Triceps"].includes(category))return"upper_body_strength";if(["Quads","Hamstrings","Glutes","Calves"].includes(category))return"lower_body_strength";if(category==="Core")return"core_strength";if(category==="Full body")return"full_body_strength";if(category==="Conditioning")return"cardio";if(category==="Mobility")return"mobility";return"full_body_strength";}
function exerciseType(category:string,name:string):ExerciseType { const n=normalizeExerciseKey(name);if(category==="Mobility")return /stretch|pose|fold/.test(n)?"flexibility":"mobility";if(category==="Conditioning")return /jump|throw|slam/.test(n)?"plyometric":"cardiovascular";if(/hold|hang|plank|wall sit/.test(n))return"stability";return"strength"; }
function movementPatterns(category:string,name:string){const n=normalizeExerciseKey(name);if(/bench|chest press|push up|floor press/.test(n))return["horizontal_push"];if(/overhead press|shoulder press|push press|handstand/.test(n))return["vertical_push"];if(/pulldown|pull up|chin up|hang/.test(n))return["vertical_pull"];if(/row/.test(n))return["horizontal_pull"];if(/deadlift|romanian|good morning|hinge|swing|pull through/.test(n))return["hinge"];if(/lunge|split squat/.test(n))return["lunge"];if(/step up|step down/.test(n))return["step"];if(/squat|leg press|leg extension/.test(n))return["squat"];if(/carry|walk on toes/.test(n))return["carry","locomotion"];if(/pallof/.test(n))return["anti_rotation"];if(/rotation|wood chop|russian twist/.test(n))return["rotation"];if(/plank|dead bug|rollout/.test(n))return["anti_extension"];if(/crunch|sit up|leg raise|knee raise/.test(n))return["spinal_flexion"];if(/jump|hop|bound/.test(n))return["jump","landing"];if(/crawl/.test(n))return["crawl"];if(category==="Mobility")return[/stretch|pose|fold/.test(n)?"stretch":"mobility"];if(category==="Conditioning")return["locomotion"];return["isolation"];}
function bodyPositions(name:string){const n=normalizeExerciseKey(name);if(/hanging|hang|pull up|chin up/.test(n))return["hanging"];if(/half kneeling/.test(n))return["half_kneeling"];if(/tall kneeling/.test(n))return["tall_kneeling"];if(/kneeling/.test(n))return["kneeling"];if(/side lying/.test(n))return["side_lying"];if(/bird dog|quadruped|fire hydrant|cat cow/.test(n))return["quadruped"];if(/bench press|floor press|glute bridge|lying|dead bug|supine/.test(n))return["supine"];if(/prone|plank|push up/.test(n))return["prone"];if(/seated|bike|rower/.test(n))return["seated"];if(/split squat|lunge/.test(n))return["split_stance"];if(/single leg/.test(n))return["single_leg"];if(/bent over|romanian|deadlift|good morning/.test(n))return["bent_over"];return["standing"];}
const aliasMap:Record<string,string[]>={"barbell romanian deadlift":["RDL","barbell RDL"],"dumbbell romanian deadlift":["DB RDL"],"standard push up":["press-up"],"standard pull up":["pull-up"],"standard chin up":["chin-up"],"ez bar curl 21s":["21s"],"dumbbell curl 21s":["dumbbell 21s"],"stationary bike":["exercise bike","indoor bike"],"posterior delt raise":["rear delt raise"]};
function aliasesFor(name:string){const n=normalizeExerciseKey(name);const derived:string[]=[];if(/romanian deadlift/i.test(name))derived.push(name.replace(/romanian deadlift/i,"RDL"));if(/rear-delt|rear delt/i.test(name))derived.push(name.replace(/rear-delt|rear delt/i,"posterior-delt"));return[...new Set([...(aliasMap[n]??[]),...derived].filter((x)=>normalizeExerciseKey(x)!==n))];}
function trackingTemplate(category:string,name:string){const n=normalizeExerciseKey(name);if(/multi position.*hold/.test(n))return"multi_position_timed_hold";if(/hold|hang|wall sit|plank$/.test(n))return"timed_hold";if(category==="Mobility")return/stretch|pose|fold/.test(n)?"mobility_duration":"mobility_reps";if(/carry/.test(n))return"loaded_carry";if(/jump rope/.test(n))return"jump_rope";if(category==="Conditioning")return/interval/.test(n)?"cardio_intervals":"cardio_session";if(/single arm|single leg|unilateral|split squat|lunge|step up|step down/.test(n))return"reps_per_side";return/[Dd]umbbell/.test(name)||/[Kk]ettlebell/.test(name)?"reps_and_weight_per_hand":"reps_and_weight";}
function musclesFor(def:Pick<ExerciseDefinition,"name"|"category">):ExerciseMuscle[]{const activation=getMuscleActivation(def);const output:ExerciseMuscle[]=[];for(const [role,ids] of Object.entries(activation) as Array<["primary"|"secondary"|"supporting",string[]]>)for(const raw of ids){const muscleId=muscleIdMap[raw]??raw;if(!muscles.some((x)=>x.id===muscleId))continue;const intensity=role==="primary"?3:role==="secondary"?2:1;output.push({muscleId,role,intensity,contributionLevel:intensity===3?"high":intensity===2?"moderate":"low",visualRegionId:`muscle-${muscleId}`});}return output;}
function accessibility(category:string,name:string,equipmentId:string){const n=normalizeExerciseKey(name);const tags:string[]=[];if(/walk|mobility|stretch|machine|wall|chair|counter/.test(n))tags.push("beginner_friendly");if(category==="Mobility"||/walk|bike|elliptical|row/.test(n))tags.push("low_impact");if(/jump|burpee|sprint|run/.test(n))tags.push("high_impact");if(equipmentId==="bodyweight"||["dumbbell","long_resistance_band","mini_band"].includes(equipmentId))tags.push("small_space");if(!/[Pp]rone|floor|plank|push-up|push up|bridge|dead bug/.test(name))tags.push("no_floor_required");if(/machine|seated|chair/.test(n))tags.push("seated_option");return[...new Set(tags)];}
function equipmentRequirements(equipmentId:string,name:string){const n=normalizeExerciseKey(name);const ids=[equipmentId];if(/weighted.vest/.test(n))ids.push("weighted_vest");if(/band.assisted.pull.up/.test(n))ids.push("pull_up_bar");if(equipmentId==="dumbbell"||equipmentId==="barbell"){if(/incline/.test(n))ids.push("adjustable_bench");else if(/decline/.test(n))ids.push("decline_bench");else if(/bench press|seal row|chest supported|preacher/.test(n))ids.push(/preacher/.test(n)?"preacher_bench":"flat_bench");}if(equipmentId==="barbell"&&/squat/.test(n))ids.push("squat_rack");if(/step.up|step.down|box jump/.test(n)&&equipmentId!=="leg_press_machine")ids.push("plyometric_box");return[...new Set(ids)].map((id)=>({equipmentId:id,required:id!=="bodyweight"}));}

function normalize(def:ExerciseDefinition|CatalogueAddition):Exercise {const name=def.name;const category=def.category;const equipmentId=resolveEquipment(def.equipment,name);const guidance=getExerciseGuidance({name,movementPattern:movementPatterns(category,name)[0]});const templateId=trackingTemplate(category,name);const template=trackingTemplates.find((x)=>x.id===templateId)!;const type=exerciseType(category,name);const isUnilateral=template.supportsSides&&/single|unilateral|split|lunge|step/.test(normalizeExerciseKey(name));const timedHold=templateId.includes("hold");const rawDifficulty="difficulty" in def?def.difficulty:/one arm|archer|handstand|olympic|snatch|jerk/.test(normalizeExerciseKey(name))?"Advanced":/wall|chair|machine|walk|stretch/.test(normalizeExerciseKey(name))?"Beginner":"Intermediate";const difficulty=rawDifficulty.toLowerCase() as Difficulty;
  return{id:slug(name),canonicalName:name,displayName:name,slug:slug(name),aliases:aliasesFor(name),shortDescription:`A ${movementPatterns(category,name)[0].replaceAll("_"," ")} exercise for ${category.toLowerCase()} training.`,instructions:[...guidance.setup,...guidance.execution],setupCues:guidance.setup,executionCues:guidance.execution.slice(0,3),breathingCues:[guidance.breathing],commonMistakes:guidance.mistakes,safetyNotes:["Use a controlled range and suitable resistance. Stop for sharp pain, dizziness, numbness, or loss of control."],muscles:musclesFor({name,category}),equipment:equipmentRequirements(equipmentId,name),categoryId:categoryId(category),exerciseType:type,exerciseTypeIds:[type],movementPatternIds:movementPatterns(category,name),bodyPositionIds:bodyPositions(name),gripIds:["none"],stanceIds:["standard"],loadPlacementIds:[equipmentId==="bodyweight"?"bodyweight":"hands"],rangeOfMotionId:timedHold?"partial_hold":"full",impactLevelId:/jump|hop|sprint|burpee|run/.test(normalizeExerciseKey(name))?"high":category==="Conditioning"?"moderate":"none",difficulty,accessibilityTags:accessibility(category,name,equipmentId),contraindicationTags:[],skillDemand:difficulty==="advanced"?4:difficulty==="intermediate"?3:1,technicalComplexity:difficulty==="advanced"?4:difficulty==="intermediate"?3:1,balanceDemand:isUnilateral?3:1,mobilityDemand:category==="Mobility"?3:2,trackingTemplateId:templateId,defaultUnits:template.defaultUnits,defaultTempo:template.supportsTempo?{notation:"2-0-1-0",eccentricSeconds:2,pauseBottomSeconds:0,concentricSeconds:1,pauseTopSeconds:0}:undefined,tempoSupport:template.supportsTempo,holdPositionIds:timedHold?["default"]:[],unilateral:isUnilateral,timedHold,cardio:type==="cardiovascular",relationships:[],tags:[category.toLowerCase(),...movementPatterns(category,name),equipmentId,...accessibility(category,name,equipmentId)],source:{sourceName:"North-authored; derived and normalized from the North legacy catalogue"},review:{state:"approved",reviewedBy:"North catalogue normalization",reviewedAt:NOW,reviewNotes:"Original North guidance normalized against the v2 taxonomy.",version:1},status:"published",createdAt:NOW,updatedAt:NOW};}

const reviewedNameKeys=new Set(reviewedExercises.flatMap((x)=>[x.canonicalName,...x.aliases].map(normalizeExerciseKey)));
const reviewedConceptKeys=new Set([...reviewedNameKeys,"romanian deadlift"]);
const generated=[...legacyExercises,...catalogueAdditions].filter((x)=>!reviewedConceptKeys.has(normalizeExerciseKey(x.name))).map(normalize);
const uniqueGenerated=[...new Map(generated.map((x)=>[normalizeExerciseKey(x.canonicalName),x])).values()];
let all=[...reviewedExercises,...uniqueGenerated].map((x)=>x.accessibilityTags.length?x:{...x,accessibilityTags:x.cardio?["low_impact"]:x.equipment.some((e)=>e.equipmentId==="bodyweight")?["small_space"]:["no_floor_required"]});

const chains=[
 ["Wall push-up","Counter push-up","Incline push-up","Knee push-up","Standard Push-Up","Tempo push-up","Deficit push-up","Weighted-vest push-up","Archer push-up","One-arm push-up"],
 ["Dead Hang","Active hang","Scapular pull-up","Flexed-arm hang","Eccentric pull-up","Band-assisted pull-up","Machine-assisted pull-up","Pull-up","Chest-to-bar pull-up","Weighted pull-up"],
 ["Chair squat","Bodyweight box squat","Back squat","Tempo back squat","Barbell Back Squat","Pause squat","Pistol squat"],
 ["Plank","Long-lever plank","RKC plank","Ab wheel rollout","Barbell rollout"],
 ["Outdoor walk","Treadmill walk","Incline treadmill walk","Outdoor run","Trail run","Outdoor hill intervals"],
];
const byName=new Map(all.map((x)=>[normalizeExerciseKey(x.canonicalName),x]));
const relationships=new Map<string,ExerciseRelationship[]>();const pushRel=(from:Exercise,to:Exercise,type:ExerciseRelationship["type"],reason:string,priority:number)=>{const item:{id:string,fromExerciseId:string,toExerciseId:string,type:ExerciseRelationship["type"],reason:string,priority:number}={id:`${from.id}_${type}_${to.id}`,fromExerciseId:from.id,toExerciseId:to.id,type,reason,priority};relationships.set(from.id,[...(relationships.get(from.id)??[]),item]);};
for(const chain of chains)for(let i=0;i<chain.length-1;i++){const from=byName.get(normalizeExerciseKey(chain[i]));const to=byName.get(normalizeExerciseKey(chain[i+1]));if(from&&to){pushRel(from,to,"progression","Increases the technical or loading demand within the same movement family.",1);pushRel(to,from,"regression","Reduces the technical or loading demand within the same movement family.",1);}}
const families=new Map<string,Exercise[]>();for(const x of all){const primary=x.muscles.find((m)=>m.role==="primary")?.muscleId;const pattern=x.movementPatternIds[0];if(!primary||!pattern)continue;const key=`${primary}:${pattern}`;families.set(key,[...(families.get(key)??[]),x]);}
for(const family of families.values())for(const exercise of family){const alternatives=family.filter((x)=>x.id!==exercise.id&&x.equipment[0]?.equipmentId!==exercise.equipment[0]?.equipmentId).slice(0,3);alternatives.forEach((to,index)=>pushRel(exercise,to,"substitution","Uses a similar movement pattern and primary muscle with different equipment.",index+1));const variations=family.filter((x)=>x.id!==exercise.id&&x.equipment[0]?.equipmentId===exercise.equipment[0]?.equipmentId).slice(0,2);variations.forEach((to,index)=>pushRel(exercise,to,"variation","Changes stance, grip, position, tempo, or loading while retaining the same movement family.",index+1));}
for(const exercise of all){if((relationships.get(exercise.id)?.length??0)>0||exercise.relationships.length>0)continue;const primary=new Set(exercise.muscles.filter((m)=>m.role==="primary").map((m)=>m.muscleId));const patternMatches=all.filter((x)=>x.id!==exercise.id&&x.movementPatternIds.some((p)=>exercise.movementPatternIds.includes(p)));const candidates=[...patternMatches.filter((x)=>x.muscles.some((m)=>m.role==="primary"&&primary.has(m.muscleId))),...patternMatches].filter((x,index,rows)=>rows.findIndex((row)=>row.id===x.id)===index).slice(0,2);candidates.forEach((to,index)=>pushRel(exercise,to,to.equipment[0]?.equipmentId===exercise.equipment[0]?.equipmentId?"variation":"substitution","Provides a closely related movement option without implying medical suitability.",index+1));}
all=all.map((x)=>({...x,relationships:[...new Map([...(x.relationships??[]),...(relationships.get(x.id)??[])].map((relationship)=>[relationship.id,relationship])).values()]}));
export const productionExerciseLibrary:Exercise[]=all;
