import type { Exercise, ExerciseMuscle, ExerciseRelationship, ExerciseType, TrackingUnit } from "./types";

const NOW = "2026-07-17T00:00:00.000Z";
const muscle = (muscleId: string, role: ExerciseMuscle["role"], intensity: 1|2|3, notes?: string): ExerciseMuscle => ({ muscleId, role, intensity, contributionLevel:intensity===3?"high":intensity===2?"moderate":"low", visualRegionId: muscleId === "front_shoulders" ? "front-delts" : muscleId === "side_shoulders" ? "side-delts" : muscleId === "rear_shoulders" ? "rear-delts" : muscleId === "lower_back" ? "lower-back" : muscleId === "upper_back" ? "traps" : muscleId === "hip_flexors" ? "hip-flexors" : muscleId, notes });
const rel = (fromExerciseId: string, toExerciseId: string, type: ExerciseRelationship["type"], reason: string, priority=1): ExerciseRelationship => ({ id:`${fromExerciseId}_${type}_${toExerciseId}`, fromExerciseId, toExerciseId, type, reason, priority });

type Seed = {
  id:string; name:string; aliases?:string[]; description:string; categoryId:string; type?:ExerciseType|"isometric"|"carry"|"cardio"|"stretch"; patterns:string[]; equipment:string[];
  muscles:ExerciseMuscle[]; tracking:string; tags:string[]; instructions:string[]; setup?:string[]; execution?:string[]; mistakes?:string[];
  safety?:string[]; positions?:string[]; grips?:string[]; stances?:string[]; load?:string[]; difficulty?:Exercise["difficulty"];
  skill?:1|2|3|4|5; balance?:1|2|3|4|5; mobility?:1|2|3|4|5; unilateral?:boolean; timedHold?:boolean; cardio?:boolean;
  units?:Partial<Record<string,TrackingUnit>>; relationships?:ExerciseRelationship[];
};

function make(seed: Seed): Exercise {
  const muscleIds:Record<string,string>={chest:"pectoralis_major",triceps:"triceps_brachii",front_shoulders:"anterior_deltoid",side_shoulders:"lateral_deltoid",rear_shoulders:"posterior_deltoid",lats:"latissimus_dorsi",upper_back:"trapezius_middle",biceps:"biceps_brachii",forearms:"forearm_flexors",abs:"rectus_abdominis",obliques:"external_obliques",lower_back:"erector_spinae",glutes:"gluteus_maximus",quads:"quadriceps",adductors:"hip_adductors",calves:"gastrocnemius",hip_flexors:"iliopsoas"};
  const equipmentIds:Record<string,string>={none:"bodyweight",bench:"flat_bench",rack:"squat_rack",cable_machine:"cable_stack",resistance_band:"long_resistance_band"};
  const trackingIds:Record<string,string>={reps_bodyweight:"reps_only",reps_weight:"reps_and_weight",reps_weight_per_side:"reps_and_weight_per_hand",carry:"loaded_carry",cardio_distance:"distance_and_time",cardio_power:"cardio_session",mobility_hold:"mobility_duration"};
  const exerciseTypes:Record<string,ExerciseType>={isometric:"stability",carry:"strength",cardio:"cardiovascular",stretch:"flexibility"};
  const patternIds:Record<string,string>={shoulder_abduction:"isolation",cycling:"locomotion",hip_hinge:"hinge"};
  const mappedTrackingId=trackingIds[seed.tracking]??seed.tracking;
  const trackingId=seed.unilateral&&mappedTrackingId==="reps_and_weight"?"reps_per_side":mappedTrackingId;
  return {
    id: seed.id, canonicalName: seed.name, displayName: seed.name, slug: seed.id, aliases: seed.aliases ?? [], shortDescription: seed.description,
    instructions: seed.instructions, setupCues: seed.setup ?? ["Set up in a stable position before beginning."], executionCues: [...(seed.execution ?? []),...seed.instructions].slice(0,3),
    breathingCues: seed.cardio ? ["Use steady breathing that matches the intended effort."] : ["Brace before effort; exhale through the hardest part."],
    commonMistakes: seed.mistakes ?? ["Rushing the movement", "Using a range that cannot be controlled"], safetyNotes: seed.safety ?? ["Stop for sharp pain, dizziness, numbness, or loss of control."],
    muscles: seed.muscles.map((item)=>({...item,muscleId:muscleIds[item.muscleId]??item.muscleId,visualRegionId:`muscle-${muscleIds[item.muscleId]??item.muscleId}`})), equipment: seed.equipment.map((equipmentId) => ({ equipmentId:equipmentIds[equipmentId]??equipmentId, required:true })), categoryId: seed.categoryId, exerciseType: exerciseTypes[seed.type??""] ?? (seed.type as ExerciseType|undefined) ?? "strength", exerciseTypeIds:[exerciseTypes[seed.type??""] ?? (seed.type as ExerciseType|undefined) ?? "strength"],
    movementPatternIds: seed.patterns.map((id)=>patternIds[id]??id), bodyPositionIds: seed.positions ?? ["standing"], gripIds: seed.grips ?? ["none"], stanceIds: seed.stances ?? ["standard"],
    loadPlacementIds: seed.load ?? [seed.equipment.includes("none") ? "bodyweight" : "hands"], rangeOfMotionId: seed.timedHold ? "partial_hold" : "full", impactLevelId: seed.cardio ? "low" : "none",
    difficulty: seed.difficulty ?? "beginner", accessibilityTags: [], contraindicationTags: [], skillDemand: seed.skill ?? 2, technicalComplexity:seed.skill??2, balanceDemand: seed.balance ?? 1, mobilityDemand: seed.mobility ?? 2,
    trackingTemplateId: trackingId, defaultUnits: seed.units ?? {}, tempoSupport:["reps_only","reps_and_weight","reps_and_weight_per_hand","reps_per_side","alternating_reps"].includes(trackingId), holdPositionIds:seed.timedHold?["default"]:[], unilateral: seed.unilateral ?? false, timedHold: seed.timedHold ?? false, cardio: seed.cardio ?? false,
    relationships: seed.relationships ?? [], tags: seed.tags, source: { sourceName:"North editorial" }, review:{ state:"approved", reviewedBy:"North exercise review", reviewedAt:NOW, version:1 },
    status:"published", createdAt:NOW, updatedAt:NOW,
  };
}

const seeds: Seed[] = [
 {id:"standard_push_up",name:"Standard Push-Up",aliases:["push up","press-up"],description:"A bodyweight horizontal press for chest, shoulders, triceps and trunk control.",categoryId:"upper_body_strength",patterns:["horizontal_push"],equipment:["none"],muscles:[muscle("chest","primary",3),muscle("triceps","secondary",2),muscle("front_shoulders","secondary",2),muscle("abs","stabilizer",2)],tracking:"reps_bodyweight",tags:["push","bodyweight","home"],instructions:["Place hands just outside shoulder width and form a straight line from head to heel.","Lower the chest between the hands while keeping elbows controlled.","Press the floor away to return to the start."],setup:["Spread the fingers and brace the glutes and abs."],execution:["Keep the chest and hips rising together."],mistakes:["Flaring elbows straight sideways","Letting the hips sag"],relationships:[rel("standard_push_up","dumbbell_bench_press","progression","Adds external load and independent implements."),rel("standard_push_up","dumbbell_bench_press","substitution","Uses the same horizontal pushing pattern.")]},
 {id:"push_up_isometric_hold",name:"Push-Up Isometric Hold",aliases:["push-up hold"],description:"A static push-up position held under tension.",categoryId:"isometric",type:"isometric",patterns:["horizontal_push","anti_extension"],equipment:["none"],muscles:[muscle("chest","primary",3),muscle("triceps","secondary",2),muscle("abs","stabilizer",3)],tracking:"timed_hold",tags:["hold","bodyweight"],instructions:["Set a strong push-up position.","Lower to the prescribed point.","Hold without losing the head-to-heel line."],timedHold:true,relationships:[rel("push_up_isometric_hold","standard_push_up","variation","Builds control at a chosen joint angle.")]},
 {id:"dead_hang",name:"Dead Hang",aliases:["bar hang"],description:"A relaxed-to-active overhead hang that trains grip and hanging tolerance.",categoryId:"isometric",type:"isometric",patterns:["vertical_pull"],equipment:["pull_up_bar"],muscles:[muscle("forearms","primary",3),muscle("lats","supporting",1),muscle("upper_back","stabilizer",1)],tracking:"timed_hold",tags:["grip","hang"],instructions:["Grip a secure bar with hands outside shoulder width.","Step clear and hang without swinging.","Finish before the grip opens unexpectedly."],positions:["hanging"],grips:["overhand","closed"],timedHold:true,relationships:[rel("dead_hang","top_pull_up_hold","progression","Adds elbow flexion and greater upper-back demand.")]},
 {id:"top_pull_up_hold",name:"Top Pull-Up Hold",aliases:["pull-up hold","chin over bar hold"],description:"An isometric hold at the top of a pull-up.",categoryId:"isometric",type:"isometric",patterns:["vertical_pull"],equipment:["pull_up_bar"],muscles:[muscle("lats","primary",3),muscle("biceps","secondary",3),muscle("upper_back","secondary",2),muscle("forearms","stabilizer",2)],tracking:"timed_hold",tags:["pull","isometric"],instructions:["Use a step to begin with the chin above the bar.","Hold the shoulders down and elbows close.","Lower under control when the hold ends."],positions:["hanging"],grips:["overhand","closed"],timedHold:true,difficulty:"intermediate",relationships:[rel("top_pull_up_hold","dead_hang","regression","Reduces elbow-flexor and pulling demand.")]},
 {id:"dumbbell_bench_press",name:"Dumbbell Bench Press",aliases:["flat dumbbell press","DB bench"],description:"A bilateral dumbbell press performed on a flat bench.",categoryId:"upper_body_strength",patterns:["horizontal_push"],equipment:["dumbbell","bench"],muscles:[muscle("chest","primary",3),muscle("triceps","secondary",2),muscle("front_shoulders","secondary",2)],tracking:"reps_weight_per_side",tags:["push","chest","dumbbell"],instructions:["Sit with dumbbells on the thighs and lie back safely.","Set shoulder blades and lower the dumbbells beside the chest.","Press up without banging the dumbbells together."],positions:["supine"],grips:["neutral","closed"],load:["hands"],difficulty:"intermediate",relationships:[rel("dumbbell_bench_press","standard_push_up","regression","Removes external load and bench setup."),rel("dumbbell_bench_press","standard_push_up","substitution","Retains a horizontal push stimulus.")]},
 {id:"dumbbell_lateral_raise",name:"Dumbbell Lateral Raise",aliases:["side raise"],description:"A shoulder abduction exercise emphasizing the side deltoids.",categoryId:"upper_body_strength",patterns:["shoulder_abduction"],equipment:["dumbbell"],muscles:[muscle("side_shoulders","primary",3),muscle("front_shoulders","synergist",1),muscle("upper_back","stabilizer",1)],tracking:"reps_weight",tags:["shoulders","dumbbell"],instructions:["Stand tall with light dumbbells by the sides.","Raise the arms in the shoulder-blade plane.","Stop near shoulder height and lower slowly."],mistakes:["Shrugging the load upward","Swinging with the torso"]},
 {id:"barbell_back_squat",name:"Barbell Back Squat",aliases:["back squat"],description:"A loaded squat with the bar supported across the upper back.",categoryId:"lower_body_strength",patterns:["squat"],equipment:["barbell","rack"],muscles:[muscle("quads","primary",3),muscle("glutes","primary",3),muscle("adductors","synergist",2),muscle("abs","stabilizer",2),muscle("lower_back","stabilizer",2)],tracking:"reps_weight",tags:["legs","barbell","compound"],instructions:["Set the rack just below shoulder height and secure the bar on the upper back.","Brace, sit between the hips and knees, and keep the whole foot grounded.","Drive up while maintaining the torso position."],stances:["shoulder_width"],load:["back"],difficulty:"intermediate",skill:4,balance:3,mobility:3,relationships:[rel("barbell_back_squat","leg_press","regression","The machine reduces balance and bar-control demands."),rel("barbell_back_squat","leg_press","substitution","Provides a knee-dominant lower-body stimulus.")]},
 {id:"barbell_romanian_deadlift",name:"Barbell Romanian Deadlift",aliases:["barbell RDL","RDL"],description:"A loaded hip hinge emphasizing hamstrings and glutes.",categoryId:"lower_body_strength",patterns:["hip_hinge"],equipment:["barbell"],muscles:[muscle("hamstrings","primary",3),muscle("glutes","primary",3),muscle("lower_back","stabilizer",2),muscle("forearms","stabilizer",2)],tracking:"reps_weight",tags:["hinge","hamstrings","barbell"],instructions:["Hold the bar close to the thighs with soft knees.","Push the hips back while keeping the spine controlled.","Stand by driving the hips forward when hamstring range ends."],grips:["overhand","closed"],load:["hands"],difficulty:"intermediate",mistakes:["Turning the movement into a squat","Letting the bar drift away"]},
 {id:"bulgarian_split_squat",name:"Bulgarian Split Squat",aliases:["rear-foot-elevated split squat"],description:"A rear-foot-elevated unilateral squat.",categoryId:"lower_body_strength",patterns:["lunge","squat"],equipment:["bench","dumbbell"],muscles:[muscle("quads","primary",3),muscle("glutes","primary",3),muscle("adductors","stabilizer",2)],tracking:"reps_weight_per_side",tags:["unilateral","legs"],instructions:["Place the rear foot on a bench and set a stable front-foot distance.","Lower mostly through the front leg.","Drive through the front foot to stand."],positions:["split_stance"],stances:["split"],unilateral:true,difficulty:"intermediate",balance:4},
 {id:"cable_pallof_press",name:"Cable Pallof Press",aliases:["Pallof press"],description:"An anti-rotation press resisting a sideways cable pull.",categoryId:"core_strength",patterns:["anti_rotation"],equipment:["cable_machine"],muscles:[muscle("obliques","primary",3),muscle("abs","primary",2),muscle("glutes","stabilizer",1)],tracking:"reps_weight",tags:["core","anti-rotation","cable"],instructions:["Stand side-on to the cable and hold the handle at the sternum.","Brace and press straight forward.","Pause without rotating, then return."],load:["cable"],unilateral:true},
 {id:"lat_pulldown",name:"Lat Pulldown",aliases:["cable pulldown"],description:"A machine-assisted vertical pull toward the upper chest.",categoryId:"upper_body_strength",patterns:["vertical_pull"],equipment:["lat_pulldown_machine"],muscles:[muscle("lats","primary",3),muscle("biceps","secondary",2),muscle("upper_back","secondary",2),muscle("forearms","stabilizer",1)],tracking:"reps_weight",tags:["back","pull","machine"],instructions:["Secure the thighs and grip the bar outside shoulder width.","Pull elbows down toward the ribs.","Return overhead under control without losing the torso position."],positions:["seated"],grips:["overhand","closed"]},
 {id:"seated_cable_row",name:"Seated Cable Row",aliases:["low cable row"],description:"A seated horizontal cable pull for the back and arms.",categoryId:"upper_body_strength",patterns:["horizontal_pull"],equipment:["seated_row_machine"],muscles:[muscle("lats","primary",3),muscle("upper_back","primary",3),muscle("biceps","secondary",2),muscle("rear_shoulders","secondary",2)],tracking:"reps_weight",tags:["back","row","cable"],instructions:["Sit tall with feet braced and arms long.","Pull the handle toward the lower ribs.","Reach forward under control without rounding aggressively."],positions:["seated"],grips:["neutral","closed"],load:["cable"]},
 {id:"leg_press",name:"Leg Press",aliases:["machine leg press"],description:"A machine squat pattern with the torso supported.",categoryId:"lower_body_strength",patterns:["squat"],equipment:["leg_press_machine"],muscles:[muscle("quads","primary",3),muscle("glutes","secondary",2),muscle("adductors","synergist",1)],tracking:"reps_weight",tags:["legs","machine"],instructions:["Set the seat so the pelvis stays supported at depth.","Lower the platform with knees tracking over the feet.","Press through the whole foot without locking violently."],positions:["seated"],load:["front"],relationships:[rel("leg_press","barbell_back_squat","progression","Adds free-weight balance, bracing and bar-control demands."),rel("leg_press","barbell_back_squat","substitution","Retains a knee-dominant lower-body stimulus.")]},
 {id:"resistance_band_face_pull",name:"Resistance Band Face Pull",aliases:["band face pull"],description:"A band pull toward the face emphasizing rear shoulders and upper back.",categoryId:"upper_body_strength",patterns:["horizontal_pull"],equipment:["resistance_band"],muscles:[muscle("rear_shoulders","primary",3),muscle("upper_back","primary",2),muscle("forearms","stabilizer",1)],tracking:"reps_bodyweight",tags:["shoulders","band","upper back"],instructions:["Anchor the band securely near face height.","Pull toward the face while separating the hands.","Return slowly without shrugging."],load:["cable"]},
 {id:"farmer_carry",name:"Farmer Carry",aliases:["farmer walk"],description:"A loaded walk with weights held at the sides.",categoryId:"full_body_strength",type:"carry",patterns:["carry","locomotion"],equipment:["dumbbell"],muscles:[muscle("forearms","primary",3),muscle("upper_back","stabilizer",2),muscle("abs","stabilizer",3),muscle("glutes","supporting",2)],tracking:"carry",tags:["carry","grip","full body"],instructions:["Stand tall with equal loads at the sides.","Walk with short controlled steps.","Turn safely and set the weights down with a hinge."],load:["sides"]},
 {id:"plank",name:"Plank",aliases:["forearm plank"],description:"A prone isometric hold resisting spinal extension.",categoryId:"isometric",type:"isometric",patterns:["anti_extension"],equipment:["none"],muscles:[muscle("abs","primary",3),muscle("obliques","secondary",2),muscle("glutes","stabilizer",2)],tracking:"timed_hold",tags:["core","hold","bodyweight"],instructions:["Place elbows beneath shoulders and extend the legs.","Brace the abs and squeeze the glutes.","Hold a straight line without holding the breath."],positions:["prone"],timedHold:true},
 {id:"jump_rope",name:"Jump Rope",aliases:["skipping rope"],description:"Rhythmic low-amplitude jumping with a rotating rope.",categoryId:"cardio",type:"cardio",patterns:["locomotion"],equipment:["jump_rope"],muscles:[muscle("calves","primary",3),muscle("quads","supporting",1),muscle("forearms","supporting",1)],tracking:"jump_rope",tags:["cardio","coordination"],instructions:["Size the rope and stand tall with elbows near the sides.","Turn mainly from the wrists.","Use quiet low jumps and land softly."],cardio:true,difficulty:"intermediate",skill:4},
 {id:"treadmill_walk",name:"Treadmill Walk",aliases:["indoor walk"],description:"Walking on a motorized treadmill at a controlled pace and incline.",categoryId:"cardio",type:"cardio",patterns:["locomotion"],equipment:["treadmill"],muscles:[muscle("quads","primary",2),muscle("glutes","secondary",2),muscle("hamstrings","supporting",1),muscle("calves","supporting",2)],tracking:"cardio_distance",tags:["walk","cardio","zone 2"],instructions:["Start the belt slowly before stepping into pace.","Walk naturally without leaning on the rails.","Reduce speed before stopping."],cardio:true},
 {id:"stationary_bike",name:"Stationary Bike",aliases:["exercise bike","indoor cycle"],description:"Low-impact cycling performed on a stationary bike.",categoryId:"cardio",type:"cardio",patterns:["cycling"],equipment:["stationary_bike"],muscles:[muscle("quads","primary",3),muscle("glutes","secondary",2),muscle("hamstrings","supporting",2),muscle("calves","supporting",1)],tracking:"cardio_power",tags:["bike","cardio","zone 2"],instructions:["Set the saddle so the knee remains slightly bent at the bottom.","Begin with light resistance.","Pedal smoothly at the intended effort."],positions:["seated"],cardio:true},
 {id:"hip_flexor_stretch",name:"Hip Flexor Stretch",aliases:["half-kneeling hip flexor stretch"],description:"A controlled half-kneeling stretch for the front of the hip.",categoryId:"mobility",type:"stretch",patterns:["stretch"],equipment:["none"],muscles:[muscle("hip_flexors","primary",2),muscle("glutes","antagonist",1)],tracking:"mobility_hold",tags:["mobility","hips","stretch"],instructions:["Kneel with one foot forward and pad the rear knee.","Tuck the pelvis gently and squeeze the rear glute.","Shift forward slightly without arching the lower back."],positions:["half_kneeling"],stances:["split"],unilateral:true,mobility:2},
];

export const reviewedExercises: Exercise[] = seeds.map(make);
