import type { Equipment, EquipmentGroup, ExerciseCategory, ExerciseTrackingTemplate, ExerciseType, MovementPattern, Muscle, MuscleVisibility, ResistanceType, Suitability, TrackingField, TrackingUnit } from "./types";

const title=(id:string)=>id.split("_").map((part)=>part==="ez"?"EZ":part[0].toUpperCase()+part.slice(1)).join(" ");
const muscle=(id:string,parentMuscleGroupId:string|undefined,bodyRegion:string,visibility:MuscleVisibility[],aliases:string[]=[],anatomicalName=title(id)):Muscle=>({
  id,displayName:title(id),commonName:title(id),anatomicalName,parentMuscleGroupId,bodyRegion,visibility,laterality:["left","right","bilateral"],
  visualSvgTargetId:`muscle-${id}`,description:`The ${title(id).toLowerCase()} region used for movement and control.`,aliases,active:true,
});

export const muscles:Muscle[]=[
  muscle("chest",undefined,"torso",["front"]),muscle("pectoralis_major","chest","torso",["front"],["pecs"]),muscle("pectoralis_major_clavicular","pectoralis_major","torso",["front"],["upper chest"]),muscle("pectoralis_major_sternal","pectoralis_major","torso",["front"],["mid chest"]),muscle("pectoralis_major_costal","pectoralis_major","torso",["front"],["lower chest"]),muscle("pectoralis_minor","chest","torso",["front"]),muscle("serratus_anterior","chest","torso",["front","side"],["serratus"]),
  muscle("shoulders",undefined,"shoulder",["front","back","side"],["delts"]),muscle("anterior_deltoid","shoulders","shoulder",["front","side"],["front delts"]),muscle("lateral_deltoid","shoulders","shoulder",["front","back","side"],["side delts"]),muscle("posterior_deltoid","shoulders","shoulder",["back","side"],["rear delts"]),muscle("rotator_cuff","shoulders","shoulder",["front","back"]),muscle("supraspinatus","rotator_cuff","shoulder",["back"]),muscle("infraspinatus","rotator_cuff","shoulder",["back"]),muscle("teres_minor","rotator_cuff","shoulder",["back"]),muscle("subscapularis","rotator_cuff","shoulder",["front"]),
  muscle("back",undefined,"torso",["back"]),muscle("latissimus_dorsi","back","torso",["back","side"],["lats"]),muscle("trapezius","back","torso",["back"],["traps"]),muscle("trapezius_upper","trapezius","upper_back",["back"]),muscle("trapezius_middle","trapezius","upper_back",["back"]),muscle("trapezius_lower","trapezius","upper_back",["back"]),muscle("rhomboids","back","upper_back",["back"]),muscle("rhomboid_major","rhomboids","upper_back",["back"]),muscle("rhomboid_minor","rhomboids","upper_back",["back"]),muscle("teres_major","back","upper_back",["back"]),muscle("erector_spinae","back","lower_back",["back"]),muscle("multifidus","back","lower_back",["back"]),muscle("quadratus_lumborum","back","lower_back",["back"],["QL"]),
  muscle("arms",undefined,"arm",["front","back"]),muscle("biceps_brachii","arms","upper_arm",["front"],["biceps"]),muscle("biceps_long_head","biceps_brachii","upper_arm",["front"]),muscle("biceps_short_head","biceps_brachii","upper_arm",["front"]),muscle("brachialis","arms","upper_arm",["front","side"]),muscle("brachioradialis","arms","forearm",["front","side"]),muscle("triceps_brachii","arms","upper_arm",["back"],["triceps"]),muscle("triceps_long_head","triceps_brachii","upper_arm",["back"]),muscle("triceps_lateral_head","triceps_brachii","upper_arm",["back","side"]),muscle("triceps_medial_head","triceps_brachii","upper_arm",["back"]),muscle("forearm_flexors","arms","forearm",["front"]),muscle("forearm_extensors","arms","forearm",["back"]),muscle("wrist_flexors","forearm_flexors","forearm",["front"]),muscle("wrist_extensors","forearm_extensors","forearm",["back"]),muscle("grip_muscles","arms","hand",["front","back"],["grip"]),
  muscle("core",undefined,"torso",["front","back","side"]),muscle("rectus_abdominis","core","torso",["front"],["abs"]),muscle("transverse_abdominis","core","torso",["front","side"],["deep core"]),muscle("external_obliques","core","torso",["front","side"],["side abs"]),muscle("internal_obliques","core","torso",["front","side"]),muscle("diaphragm","core","torso",["front","side"]),muscle("pelvic_floor","core","pelvis",["front","back"]),muscle("spinal_stabilizers","core","torso",["back"]),
  muscle("hips_glutes",undefined,"hips",["front","back","side"],["hips"]),muscle("gluteus_maximus","hips_glutes","hips",["back","side"],["glutes"]),muscle("gluteus_medius","hips_glutes","hips",["back","side"]),muscle("gluteus_minimus","hips_glutes","hips",["side"]),muscle("tensor_fasciae_latae","hips_glutes","hips",["front","side"],["TFL"]),muscle("iliopsoas","hips_glutes","hips",["front"]),muscle("iliacus","iliopsoas","hips",["front"]),muscle("psoas_major","iliopsoas","hips",["front"]),muscle("hip_adductors","hips_glutes","upper_leg",["front","side"],["inner thighs"]),muscle("adductor_longus","hip_adductors","upper_leg",["front"]),muscle("adductor_brevis","hip_adductors","upper_leg",["front"]),muscle("adductor_magnus","hip_adductors","upper_leg",["front","back"]),muscle("gracilis","hip_adductors","upper_leg",["front"]),muscle("pectineus","hip_adductors","upper_leg",["front"]),muscle("hip_abductors","hips_glutes","hips",["side"]),muscle("piriformis","hips_glutes","hips",["back"]),muscle("deep_hip_rotators","hips_glutes","hips",["back"]),
  muscle("quadriceps",undefined,"upper_leg",["front"],["quads"]),muscle("rectus_femoris","quadriceps","upper_leg",["front"]),muscle("vastus_lateralis","quadriceps","upper_leg",["front","side"]),muscle("vastus_medialis","quadriceps","upper_leg",["front"]),muscle("vastus_intermedius","quadriceps","upper_leg",["front"]),
  muscle("hamstrings",undefined,"upper_leg",["back"]),muscle("biceps_femoris_long_head","hamstrings","upper_leg",["back"]),muscle("biceps_femoris_short_head","hamstrings","upper_leg",["back"]),muscle("semitendinosus","hamstrings","upper_leg",["back"]),muscle("semimembranosus","hamstrings","upper_leg",["back"]),
  muscle("lower_leg",undefined,"lower_leg",["front","back","side"]),muscle("gastrocnemius","lower_leg","lower_leg",["back","side"],["calves"]),muscle("soleus","lower_leg","lower_leg",["back"]),muscle("tibialis_anterior","lower_leg","lower_leg",["front"],["shins"]),muscle("fibularis_longus","lower_leg","lower_leg",["side"]),muscle("fibularis_brevis","lower_leg","lower_leg",["side"]),muscle("tibialis_posterior","lower_leg","lower_leg",["back"]),
  muscle("neck",undefined,"neck",["front","back","side"]),muscle("sternocleidomastoid","neck","neck",["front","side"],["SCM"]),muscle("neck_flexors","neck","neck",["front"]),muscle("neck_extensors","neck","neck",["back"]),
];

const equipmentGroups:Record<EquipmentGroup,string[]>={
  no_equipment:["bodyweight","floor","wall","doorway","stairs","hill","partner"],
  free_weights:["dumbbell","adjustable_dumbbell","barbell","ez_curl_bar","trap_bar","safety_squat_bar","swiss_bar","cambered_bar","kettlebell","weight_plate","medicine_ball","slam_ball","sandbag","mace","club","ankle_weights","weighted_vest"],
  benches_and_supports:["exercise_mat","flat_bench","adjustable_bench","incline_bench","decline_bench","preacher_bench","roman_chair","hyperextension_bench","glute_ham_developer","squat_rack","power_rack","smith_machine","plyometric_box","aerobic_step","step_platform","stability_ball","bosu","foam_roller","yoga_block"],
  bands_and_cables:["loop_band","mini_band","long_resistance_band","resistance_tube","assisted_pull_up_band","suspension_trainer","cable_stack","functional_trainer","high_pulley","low_pulley","lat_pulldown_station","ankle_cuff","wrist_cuff","rope_attachment","straight_bar_attachment","ez_bar_attachment","v_bar_attachment","single_handle_attachment","lat_bar_attachment"],
  gym_machines:["chest_press_machine","incline_chest_press_machine","pec_deck","reverse_pec_deck","shoulder_press_machine","lateral_raise_machine","lat_pulldown_machine","seated_row_machine","high_row_machine","low_row_machine","assisted_pull_up_dip_machine","leg_press_machine","hack_squat_machine","pendulum_squat_machine","belt_squat_machine","leg_extension_machine","seated_leg_curl_machine","lying_leg_curl_machine","standing_leg_curl_machine","hip_thrust_machine","glute_drive_machine","hip_abductor_machine","hip_adductor_machine","calf_raise_machine","rotary_torso_machine","abdominal_crunch_machine","back_extension_machine","preacher_curl_machine","biceps_curl_machine","triceps_extension_machine","dip_machine"],
  cardio_equipment:["treadmill","manual_treadmill","stationary_bike","spin_bike","recumbent_bike","air_bike","rowing_machine","ski_erg","elliptical","stair_climber","step_mill","arc_trainer","versaclimber","jacobs_ladder"],
  conditioning:["battle_ropes","jump_rope","speed_rope","heavy_rope","sled","prowler","tire","sledgehammer","agility_ladder","cones","hurdles","parallettes","pull_up_bar","dip_bars","gymnastics_rings","climbing_rope","heavy_bag"],
};
const resistanceFor=(group:EquipmentGroup,id:string):ResistanceType=>group==="no_equipment"?(id==="partner"?"partner":id==="bodyweight"?"bodyweight":"none"):group==="free_weights"||group==="benches_and_supports"?"free_weight":group==="bands_and_cables"?(id.includes("band")||id.includes("tube")?"elastic":"cable"):group==="gym_machines"?(id.includes("smith")?"plate_loaded":"selectorized"):group==="cardio_equipment"?(id.includes("air")?"air":id.includes("manual")?"friction":"motorized"):"gravity";
const suitabilityFor=(group:EquipmentGroup):Suitability[]=>group==="no_equipment"?["home","gym","outdoor"]:group==="free_weights"||group==="benches_and_supports"||group==="bands_and_cables"?["home","gym"]:group==="conditioning"?["gym","outdoor"]:["gym"];
const equipmentAliases:Record<string,string[]>={bodyweight:["no equipment"],dumbbell:["DB","dumbbells"],barbell:["BB"],ez_curl_bar:["EZ bar"],flat_bench:["bench"],cable_stack:["cable machine"],functional_trainer:["dual cable"],stationary_bike:["exercise bike"],jump_rope:["skipping rope"],pull_up_bar:["chin-up bar"]};
export const equipment:Equipment[]=Object.entries(equipmentGroups).flatMap(([group,ids])=>ids.map((id)=>({id,displayName:title(id),equipmentGroup:group as EquipmentGroup,aliases:equipmentAliases[id]??[],suitability:suitabilityFor(group as EquipmentGroup),resistanceType:resistanceFor(group as EquipmentGroup,id),iconRef:`equipment-${id}`,active:true})));

export const movementPatterns:MovementPattern[]=["horizontal_push","vertical_push","horizontal_pull","vertical_pull","squat","hinge","lunge","step","carry","rotation","anti_rotation","spinal_flexion","spinal_extension","lateral_flexion","anti_extension","anti_flexion","anti_lateral_flexion","locomotion","jump","landing","throw","crawl","climb","isolation","mobility","stretch","balance","breathing","isometric","acceleration","deceleration","change_of_direction"].map((id)=>({id,displayName:title(id),active:true}));
export const exerciseTypes:ExerciseType[]=["strength","hypertrophy","muscular_endurance","cardiovascular","power","plyometric","speed","agility","mobility","flexibility","stability","balance","rehabilitation","warm_up","cool_down","recovery","sport_specific","skill_practice","breathing"];
export const bodyPositions=["standing","seated","supine","prone","side_lying","kneeling","half_kneeling","tall_kneeling","quadruped","hanging","supported","incline","decline","bent_over","split_stance","staggered_stance","single_leg"] as const;
export const accessibilityTags=["beginner_friendly","low_impact","high_impact","seated_option","chair_supported","wheelchair_compatible","limited_grip_option","limited_overhead_mobility_option","reduced_knee_flexion","reduced_spinal_loading","no_floor_required","no_kneeling","no_wrist_extension","small_space","prenatal_consideration","postpartum_consideration","pelvic_floor_consideration","older_adult_friendly","return_to_training","youth_supervision_recommended"] as const;

const unitMap:Record<string,TrackingUnit[]>={reps:["reps"],weight:["kg","lb"],assistance_weight:["kg","lb"],added_weight:["kg","lb"],duration:["seconds","minutes"],top_duration:["seconds"],midpoint_duration:["seconds"],bottom_duration:["seconds"],distance:["metres","feet","yards","kilometres","miles"],pace:["min_per_km","min_per_mile"],speed:["km_per_hour","miles_per_hour"],calories:["kilocalories"],heart_rate:["bpm"],max_heart_rate:["bpm"],heart_rate_zone:["heart_rate_zone"],elevation_gain:["metres_elevation"],incline:["percent_incline"],watts:["watts"],peak_watts:["watts"],rpm:["rpm"],cadence:["rpm","steps"],rounds:["rounds"],steps:["steps"],double_unders:["reps"],trips:["reps"],discomfort:["rpe"],rpe:["rpe"],rir:["rir"],work_duration:["seconds","minutes"],rest_duration:["seconds","minutes"],position:["none"],side:["none"],grip:["none"],notes:["none"],cycles:["reps"],flights:["steps"]};
const trackingField=(id:string,required:boolean,perSide=false):TrackingField=>({id,label:title(id),valueType:["notes","position","side","grip"].includes(id)?"text":id.includes("duration")?"duration":"decimal",units:unitMap[id],defaultUnit:unitMap[id][0],required,perSide,minimum:["rpe","discomfort"].includes(id)?1:0,maximum:["rpe","discomfort"].includes(id)?10:undefined});
type TemplateSpec={id:string;required:string[];optional?:string[];sides?:boolean;tempo?:boolean;assistance?:boolean;added?:boolean;heart?:boolean;intervals?:boolean;rounds?:boolean};
const specs:TemplateSpec[]=[
 {id:"reps_only",required:["reps"],optional:["rpe","rir"],tempo:true},{id:"reps_and_weight",required:["weight","reps"],optional:["rpe","rir"],tempo:true,added:true},{id:"reps_and_weight_per_hand",required:["weight","reps"],optional:["rpe"],sides:true,tempo:true,added:true},
 {id:"reps_per_side",required:["reps"],optional:["weight","rpe","rir"],sides:true,tempo:true},{id:"alternating_reps",required:["reps"],optional:["weight","rpe","rir"],sides:true,tempo:true},{id:"timed_hold",required:["duration"],optional:["position","rounds","added_weight","assistance_weight","grip","rpe"],sides:true,assistance:true,added:true,rounds:true},
 {id:"multi_position_timed_hold",required:["top_duration","midpoint_duration","bottom_duration"],optional:["duration","rounds","added_weight","assistance_weight","grip","rpe"],sides:true,assistance:true,added:true,rounds:true},{id:"distance_and_time",required:["distance","duration"],optional:["pace","speed","calories","heart_rate","max_heart_rate","heart_rate_zone","elevation_gain","incline","cadence","rpe"],heart:true},{id:"cardio_session",required:["duration"],optional:["distance","pace","speed","calories","heart_rate","max_heart_rate","heart_rate_zone","elevation_gain","incline","watts","peak_watts","rpm","cadence","rpe"],heart:true},
 {id:"cardio_intervals",required:["rounds","work_duration","rest_duration"],optional:["distance","pace","speed","calories","heart_rate","max_heart_rate","heart_rate_zone","elevation_gain","incline","watts","peak_watts","rpm","cadence"],heart:true,intervals:true,rounds:true},{id:"loaded_carry",required:["weight","distance"],optional:["duration","rounds","side","heart_rate"],sides:true,heart:true,added:true,rounds:true},{id:"jump_rope",required:["duration"],optional:["rounds","steps","work_duration","rest_duration","double_unders","trips","calories","heart_rate","max_heart_rate","heart_rate_zone"],heart:true,intervals:true,rounds:true},
 {id:"steps_and_flights",required:["steps"],optional:["flights","duration","heart_rate"],heart:true},{id:"mobility_duration",required:["duration"],optional:["side","rounds","discomfort","notes"],sides:true,rounds:true},{id:"mobility_reps",required:["reps"],optional:["duration","side","rounds","discomfort","notes"],sides:true,tempo:true,rounds:true},{id:"breathing_cycles",required:["cycles"],optional:["duration"]},
 {id:"power_output",required:["watts","duration"],optional:["rpm","heart_rate","rpe"],heart:true,intervals:true},{id:"circuit_rounds",required:["rounds"],optional:["duration","rpe"],intervals:true,rounds:true},{id:"amrap",required:["duration","rounds"],optional:["reps","rpe"],intervals:true,rounds:true},{id:"emom",required:["duration","reps"],optional:["weight","rounds"],intervals:true,rounds:true},{id:"custom_tracking",required:[],optional:["reps","weight","duration","distance","rounds","heart_rate","rpe","notes"],sides:true,tempo:true,assistance:true,added:true,heart:true,intervals:true,rounds:true},
];
export const trackingTemplates:ExerciseTrackingTemplate[]=specs.map((spec)=>{const requiredFieldIds=spec.required;const optionalFieldIds=spec.optional??[];const fields=[...requiredFieldIds.map((id)=>trackingField(id,true,spec.sides)),...optionalFieldIds.map((id)=>trackingField(id,false,spec.sides))];const supportedUnits=[...new Set(fields.flatMap((x)=>x.units))];return{id:spec.id,name:title(spec.id),fields,requiredFieldIds,optionalFieldIds,supportedUnits,defaultUnits:Object.fromEntries(fields.map((x)=>[x.id,x.defaultUnit])),supportsSides:!!spec.sides,supportsTempo:!!spec.tempo,supportsAssistanceWeight:!!spec.assistance,supportsAddedWeight:!!spec.added,supportsHeartRate:!!spec.heart,supportsIntervals:!!spec.intervals,supportsWarmups:["reps_and_weight","reps_and_weight_per_hand"].includes(spec.id),supportsRounds:!!spec.rounds};});

export const categories:ExerciseCategory[]=[
  {id:"upper_body_strength",name:"Upper body strength",exerciseType:"strength"},{id:"lower_body_strength",name:"Lower body strength",exerciseType:"strength"},{id:"core_strength",name:"Core strength",exerciseType:"strength"},{id:"full_body_strength",name:"Full body strength",exerciseType:"strength"},{id:"cardio",name:"Cardio",exerciseType:"cardiovascular"},{id:"mobility",name:"Mobility",exerciseType:"mobility"},{id:"isometric",name:"Isometric",exerciseType:"stability"},
];
export const referenceIds={bodyPositions,grips:["none","overhand","neutral","closed"],stances:["standard","shoulder_width","split","staggered"],loadPlacements:["bodyweight","hands","back","front","sides","cable"],rangesOfMotion:["full","partial_hold","comfortable"],impactLevels:["none","low","moderate","high"]} as const;
