import type { Exercise, ExerciseDatabase, ExerciseTrackingTemplate, TrackingUnit } from "./types";

export type SetKind="warm_up"|"working"|"back_off"|"drop"|"failure"|"amrap";
export type WeightMeaning="per_implement"|"total_load";
export interface LoggedTrackingSet { weight?:string; reps?:string; complete:boolean; values?:Record<string,string|number|boolean>; units?:Record<string,TrackingUnit>; setKind?:SetKind; weightMeaning?:WeightMeaning; sameBothSides?:boolean; tempo?:string; restSeconds?:number; notes?:string; }
export interface UnitPreferences { weight:"kg"|"lb"; distance:"kilometres"|"miles"; shortDistance:"metres"|"feet"|"yards"; pace:"min_per_km"|"min_per_mile"; }
const KG_PER_LB=.45359237, METRES_PER_MILE=1609.344, METRES_PER_FOOT=.3048, METRES_PER_YARD=.9144, KM_PER_MILE=1.609344;
export function toCanonical(value:number,unit:TrackingUnit){if(unit==="lb")return{value:value*KG_PER_LB,unit:"kg" as TrackingUnit};if(unit==="miles")return{value:value*METRES_PER_MILE,unit:"metres" as TrackingUnit};if(unit==="kilometres")return{value:value*1000,unit:"metres" as TrackingUnit};if(unit==="feet")return{value:value*METRES_PER_FOOT,unit:"metres" as TrackingUnit};if(unit==="yards")return{value:value*METRES_PER_YARD,unit:"metres" as TrackingUnit};if(unit==="min_per_mile")return{value:value/KM_PER_MILE,unit:"min_per_km" as TrackingUnit};if(unit==="miles_per_hour")return{value:value*KM_PER_MILE,unit:"km_per_hour" as TrackingUnit};return{value,unit};}
export function fromCanonical(value:number,canonical:TrackingUnit,display:TrackingUnit){if(canonical==="kg"&&display==="lb")return value/KG_PER_LB;if(canonical==="metres"&&display==="miles")return value/METRES_PER_MILE;if(canonical==="metres"&&display==="kilometres")return value/1000;if(canonical==="metres"&&display==="feet")return value/METRES_PER_FOOT;if(canonical==="metres"&&display==="yards")return value/METRES_PER_YARD;if(canonical==="min_per_km"&&display==="min_per_mile")return value*KM_PER_MILE;if(canonical==="km_per_hour"&&display==="miles_per_hour")return value/KM_PER_MILE;return value;}
export const defaultUnitPreferences=(metric:boolean):UnitPreferences=>({weight:metric?"kg":"lb",distance:metric?"kilometres":"miles",shortDistance:metric?"metres":"feet",pace:metric?"min_per_km":"min_per_mile"});
export function templateFor(database:Pick<ExerciseDatabase,"trackingTemplates">,exercise?:Exercise|null):ExerciseTrackingTemplate|undefined{return database.trackingTemplates.find((x)=>x.id===(exercise?.trackingTemplateId??"reps_and_weight"));}
export function createTrackingSet(exercise:Exercise,template:ExerciseTrackingTemplate):LoggedTrackingSet {const values:Record<string,string|number|boolean>={};for(const field of template.fields)values[field.id]="";if(template.supportsSides)for(const field of template.fields){values[`${field.id}_left`]="";values[`${field.id}_right`]="";}const units=Object.fromEntries(Object.entries(template.defaultUnits).filter((entry):entry is [string,TrackingUnit]=>Boolean(entry[1])));return{weight:"",reps:"",complete:false,values,units,setKind:"working",weightMeaning:exercise.equipment.some((x)=>["dumbbell","kettlebell"].includes(x.equipmentId))?"per_implement":"total_load",sameBothSides:true,tempo:exercise.defaultTempo?.notation??"",restSeconds:0,notes:""};}
export function legacyCompatibleSet(set:LoggedTrackingSet):LoggedTrackingSet {const values={...(set.values??{})};if(set.weight&&!values.weight)values.weight=set.weight;if(set.reps&&!values.reps)values.reps=set.reps;return{...set,values,setKind:set.setKind??"working",weightMeaning:set.weightMeaning??"total_load",units:set.units??{}};}
const number=(value:unknown)=>{const parsed=Number.parseFloat(String(value??""));return Number.isFinite(parsed)?parsed:0;};
const durationLabel=(seconds:number)=>seconds>=60?`${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,"0")}`:`${seconds}s`;
const holdDuration=(values:Record<string,string|number|boolean>)=>number(values.duration)||number(values.top_duration)+number(values.midpoint_duration)+number(values.bottom_duration);
export function summarizeTrackingSet(exercise:Exercise,set:LoggedTrackingSet,preferences:UnitPreferences){const current=legacyCompatibleSet(set),v=current.values??{};const weight=number(v.weight||current.weight),reps=number(v.reps||current.reps),duration=holdDuration(v),distance=number(v.distance);if(exercise.trackingTemplateId==="timed_hold"||exercise.trackingTemplateId==="multi_position_timed_hold"){const position=String(v.position||exercise.holdPositionIds[0]||"").replaceAll("_"," ");return`${durationLabel(duration)}${position&&position!=="default"?` ${position}`:" hold"}${number(v.added_weight)?` + ${number(v.added_weight)} ${current.units?.added_weight??preferences.weight}`:""}`;}if(exercise.trackingTemplateId==="loaded_carry")return`${distance} ${current.units?.distance??preferences.shortDistance} carry · ${weight} ${current.units?.weight??preferences.weight}${current.weightMeaning==="per_implement"?" per hand":" total"}`;if(exercise.trackingTemplateId==="jump_rope")return`${number(v.rounds)||1} rounds · ${number(v.steps)||number(v.reps)} skips${duration?` · ${durationLabel(duration)}`:""}`;if(exercise.cardio)return`${distance?`${distance} ${current.units?.distance??preferences.distance} in `:""}${durationLabel(duration)}`;if(exercise.unilateral){const left=number(v.reps_left),right=number(v.reps_right);return`${left} left / ${right} right${weight?` · ${weight} ${current.units?.weight??preferences.weight}`:""}`;}return`${weight?`${weight} ${current.units?.weight??preferences.weight} × `:""}${reps||"—"} reps`;}
export function calculateExerciseProgress(exercise:Exercise,sets:LoggedTrackingSet[]){const completed=sets.filter((x)=>x.complete).map(legacyCompatibleSet),values=completed.map((x)=>x.values??{});if(exercise.cardio){const paces=values.map((x)=>number(x.pace)).filter((value)=>value>0);return{kind:"cardio",longestDuration:Math.max(0,...values.map((x)=>number(x.duration))),longestDistance:Math.max(0,...values.map((x)=>number(x.distance))),fastestPace:paces.length?Math.min(...paces):0,averageHeartRate:average(values.map((x)=>number(x.heart_rate))),averageWatts:average(values.map((x)=>number(x.watts)))}}if(exercise.timedHold)return{kind:"timed_hold",longestHold:Math.max(0,...values.map(holdDuration)),totalHold:values.reduce((sum,x)=>sum+holdDuration(x),0),addedWeightRecord:Math.max(0,...values.map((x)=>number(x.added_weight)))};if(exercise.unilateral)return{kind:"unilateral",leftTotal:values.reduce((sum,x)=>sum+number(x.reps_left),0),rightTotal:values.reduce((sum,x)=>sum+number(x.reps_right),0),imbalancePercent:sideImbalance(values)};const performances=completed.map((x)=>({weight:number(x.values?.weight||x.weight),reps:number(x.values?.reps||x.reps)}));return{kind:"strength",bestLoad:Math.max(0,...performances.map((x)=>x.weight)),bestRepsAtLoad:Math.max(0,...performances.filter((x)=>x.weight===Math.max(0,...performances.map((p)=>p.weight))).map((x)=>x.reps)),volume:performances.reduce((sum,x)=>sum+x.weight*x.reps,0),estimatedOneRepMax:exercise.trackingTemplateId.includes("weight")?Math.max(0,...performances.filter((x)=>x.reps>0&&x.reps<=15).map((x)=>x.weight*(1+x.reps/30))):null};}
const average=(values:number[])=>{const valid=values.filter(Boolean);return valid.length?valid.reduce((a,b)=>a+b,0)/valid.length:0;};
const sideImbalance=(values:Record<string,string|number|boolean>[])=>{const left=values.reduce((s,x)=>s+number(x.reps_left),0),right=values.reduce((s,x)=>s+number(x.reps_right),0);return Math.max(left,right)?Math.abs(left-right)/Math.max(left,right)*100:0;};
export function swapReasons(from:Exercise,to:Exercise){const reasons:string[]=[];const fromPrimary=from.muscles.filter((x)=>x.role==="primary").map((x)=>x.muscleId);if(to.muscles.some((x)=>x.role==="primary"&&fromPrimary.includes(x.muscleId)))reasons.push("same primary muscles");if(to.movementPatternIds.some((x)=>from.movementPatternIds.includes(x)))reasons.push("same movement pattern");if(to.equipment.length<from.equipment.length)reasons.push("less equipment");for(const tag of [["low_impact","lower impact"],["beginner_friendly","easier progression"],["reduced_spinal_loading","reduced spinal loading"],["no_floor_required","no floor required"]] as const)if(to.accessibilityTags.includes(tag[0]))reasons.push(tag[1]);return reasons;}
