import { memo, useMemo, useState, type FocusEvent, type MouseEvent } from "react";
import { anatomyPaths, displayNameFor, resolveVisualActivation, type AnatomySide, type VisualActivation, type VisualActivationMap, type VisualRole } from "./anatomyVisualMap";

export type AnatomyFilter="all"|"primary"|"secondary"|"supporting"|"stabilizer"|"antagonist";
export type AnatomyMapProps={activation?:VisualActivationMap;primary?:string[];secondary?:string[];synergist?:string[];supporting?:string[];stabilizer?:string[];antagonist?:string[];compact?:boolean;showBack?:boolean;label?:string;visibility?:"primary"|"all";initialFilter?:AnatomyFilter;};
const legacyActivation=(props:AnatomyMapProps):VisualActivationMap=>Object.fromEntries(([...[...(props.antagonist??[])].map((id)=>[id,{role:"antagonist",contribution:"low"}]),...[...(props.stabilizer??[])].map((id)=>[id,{role:"stabilizer",contribution:"low"}]),...[...(props.supporting??[])].map((id)=>[id,{role:"supporting",contribution:"low"}]),...[...(props.synergist??[])].map((id)=>[id,{role:"synergist",contribution:"moderate"}]),...[...(props.secondary??[])].map((id)=>[id,{role:"secondary",contribution:"moderate"}]),...[...(props.primary??[])].map((id)=>[id,{role:"primary",contribution:"high"}])] as Array<[string,VisualActivation]>));
const roleLabel=(role:VisualRole)=>role==="stabilizer"?"Stabilizer":role[0].toUpperCase()+role.slice(1);
const filterMatches=(filter:AnatomyFilter,role:VisualRole)=>filter==="all"?role!=="antagonist":filter==="supporting"?(role==="supporting"||role==="synergist"):role===filter;

function BodyFrame({side,activation,filter,selected,onSelect}:{side:AnatomySide;activation:VisualActivationMap;filter:AnatomyFilter;selected?:string;onSelect:(id:string)=>void}){const paths=anatomyPaths.filter((path)=>path.side===side);const activate=(id:string,event:MouseEvent|FocusEvent)=>{event.stopPropagation();onSelect(id)};return <div className={`holo-body-frame ${side}`}><small>{side.toUpperCase()}</small><svg viewBox="0 0 200 400" role="group" aria-label={`${side} anatomical muscle view`}>
  <defs><linearGradient id={`holo-skin-${side}`} x1="0" y1="0" x2="1" y2="1"><stop stopColor="currentColor" stopOpacity=".18"/><stop offset="1" stopColor="currentColor" stopOpacity=".04"/></linearGradient><filter id={`holo-glow-${side}`} x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
  <g className="holo-ambient" aria-hidden="true"><ellipse cx="100" cy="210" rx="78" ry="186"/><path d="M30 96H170M25 160H175M22 224H178M27 288H173M38 350H162"/></g>
  <g className="holo-silhouette" aria-hidden="true"><path d="M100 18C83 18 74 31 76 47C77 57 83 64 87 68C72 70 63 75 55 84C45 95 39 112 36 132L25 207L38 211L55 151L61 211L52 303L62 378H80L89 303L100 228L111 303L120 378H138L148 303L139 211L145 151L162 211L175 207L164 132C161 112 155 95 145 84C137 75 128 70 113 68C117 64 123 57 124 47C126 31 117 18 100 18Z"/></g>
  <g className="holo-skeleton" aria-hidden="true"><circle cx="100" cy="43" r="18"/><path d="M100 62V211M64 88L100 104L136 88M69 109L100 126L131 109M58 99L42 204M142 99L158 204M80 211L100 224L120 211M86 229L70 371M114 229L130 371"/><path d="M87 78Q100 88 113 78M78 138Q100 151 122 138M78 158Q100 171 122 158M80 181Q100 191 120 181"/></g>
  <g className="holo-inactive-muscles" aria-hidden="true">{paths.map((path)=><path key={`inactive-${path.id}`} d={path.d}/>)}</g>
  <g className="holo-active-muscles">{paths.map((path)=>{const active=activation[path.id],selectedState=selected===path.id,dimmed=active&&!filterMatches(filter,active.role);return <path key={path.id} id={`muscle-${path.id}-${side}`} data-muscle-id={path.id} d={path.d} tabIndex={active?0:-1} role={active?"button":undefined} aria-label={active?`${displayNameFor(path.id)}, ${roleLabel(active.role)}, ${active.contribution} contribution`:undefined} aria-pressed={selectedState||undefined} className={`holo-muscle ${active?`role-${active.role} contribution-${active.contribution}`:"inactive"}${selectedState?" selected":""}${dimmed?" dimmed":""}`} onMouseEnter={active?(event)=>activate(path.id,event):undefined} onFocus={active?(event)=>activate(path.id,event):undefined} onClick={active?(event)=>activate(path.id,event):undefined} onKeyDown={active?(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onSelect(path.id)}}:undefined}/>})}</g>
  <g className="holo-depth" aria-hidden="true"><path d="M31 122H169M24 208H176M33 294H167"/><rect x="18" y="12" width="164" height="376" rx="82"/></g><g className="holo-scan" aria-hidden="true"><path d="M28 76H172"/></g>
 </svg></div>}

function AnatomyMap(props:AnatomyMapProps){
 const {activation:providedActivation,primary,secondary,synergist,supporting,stabilizer,antagonist,compact=false,showBack=true,label="Muscle focus",visibility="all"}=props;
 const [chosenFilter,setFilter]=useState<AnatomyFilter>(props.initialFilter??"all");
 const [selected,setSelected]=useState<string>();
 const legacyInput=useMemo(()=>legacyActivation({primary,secondary,synergist,supporting,stabilizer,antagonist}),[primary,secondary,synergist,supporting,stabilizer,antagonist]);
 const input=providedActivation??legacyInput;
 const filter:AnatomyFilter=visibility==="primary"?"primary":chosenFilter;
 const activation=useMemo(()=>resolveVisualActivation(input,(id)=>{if(import.meta.env.DEV)console.warn(`[North anatomy] No SVG path or parent fallback for muscle: ${id}`)}),[input]);
 const entries=Object.entries(activation).filter(([,value])=>filterMatches(filter,value.role)).sort((a,b)=>({primary:0,secondary:1,synergist:2,supporting:3,stabilizer:4,antagonist:5}[a[1].role]-{primary:0,secondary:1,synergist:2,supporting:3,stabilizer:4,antagonist:5}[b[1].role]));
 const selectedActivation=selected?activation[selected]:undefined;
 const select=(id:string)=>setSelected((current)=>current===id?undefined:id);
 return <div className={`anatomy-map holo-anatomy ${compact?"compact":"detailed"}`} data-filter={filter}>
  {!compact&&<div className="holo-role-filters" role="toolbar" aria-label="Filter muscle roles">{(["all","primary","secondary","supporting","stabilizer","antagonist"] as AnatomyFilter[]).map((item)=><button type="button" key={item} aria-pressed={filter===item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item==="all"?"All":item==="stabilizer"?"Stabilizers":item==="antagonist"?"Antagonists":item[0].toUpperCase()+item.slice(1)}</button>)}</div>}
  <div className="anatomy-figures"><BodyFrame side="front" activation={activation} filter={filter} selected={selected} onSelect={select}/>{showBack&&<BodyFrame side="back" activation={activation} filter={filter} selected={selected} onSelect={select}/>}</div>
 {compact?<span className="anatomy-caption">{label}</span>:<><div className="anatomy-legend" aria-hidden="true">{(["primary","secondary","synergist","supporting","stabilizer"] as VisualRole[]).map((role)=><span key={role}><i className={`role-${role}`}/>{roleLabel(role)}</span>)}</div><div className="anatomy-muscle-list">{entries.map(([id,value])=><button type="button" key={id} data-muscle-id={id} className={`role-${value.role}${selected===id?" selected":""}`} aria-pressed={selected===id} onMouseEnter={()=>setSelected(id)} onFocus={()=>setSelected(id)} onClick={()=>select(id)}><i/><span>{displayNameFor(id)}</span><small>{value.contribution}</small><b>{roleLabel(value.role)}</b></button>)}</div>{selected&&selectedActivation&&<aside className={`anatomy-selection role-${selectedActivation.role}`} role="status" aria-live="polite"><strong>{displayNameFor(selected)}</strong><span>{roleLabel(selectedActivation.role)} muscle with {selectedActivation.contribution} contribution for this movement.</span></aside>}</>}
 </div>}
export default memo(AnatomyMap);
