import { useEffect, useRef } from "react";
import { ArrowLeft, HeartPulse } from "lucide-react";
import { NORTH_LEGAL_NOTICE_VERSION } from "../data/account";

export default function LegalNotice({ onBack }: { onBack: () => void }) {
  const headingRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => headingRef.current?.focus(), []);
  return <section className="screen destination-screen legal-screen">
    <button className="back-button" onClick={onBack}><ArrowLeft size={17}/> Back</button>
    <header className="legal-header"><p className="eyebrow">LEGAL &amp; SAFETY</p><h1 ref={headingRef} tabIndex={-1}>Use North with judgement.</h1><p>Effective August 4, 2026 · {NORTH_LEGAL_NOTICE_VERSION.replace("interim-v", "Interim notice v")}</p></header>
    <aside className="legal-review-notice"><strong>Important drafting status</strong><p>This is North's current good-faith legal and safety notice. It is not a substitute for advice from qualified counsel and must be reviewed against the operator's legal entity, location, users, data practices and applicable law before commercial launch.</p></aside>
    <section className="legal-emergency"><HeartPulse size={24}/><div><strong>Emergency or serious symptoms?</strong><p>Stop activity and contact local emergency services now for chest pain, severe trouble breathing, fainting, sudden weakness, severe injury, or any symptom that may be urgent. Do not wait for North or Nova to respond.</p></div></section>
    <nav className="legal-contents" aria-label="Legal notice contents"><a href="#legal-purpose">Purpose</a><a href="#legal-health">Health &amp; safety</a><a href="#legal-risk">Your responsibility</a><a href="#legal-ai">Nova &amp; data</a><a href="#legal-liability">Liability</a><a href="#legal-contact">Contact</a></nav>
    <div className="legal-document">
      <section id="legal-purpose"><h2>1. Purpose and acceptance</h2><p>North is a fitness planning, education, self-tracking and recordkeeping tool. It offers general guidance to help you organize workouts, reflect on activity and understand records you or connected services provide. Creating a new account requires explicit agreement to this version of the notice. If you do not agree, do not use North or create an account.</p></section>
      <section id="legal-health"><h2>2. Not medical care or individualized professional advice</h2><p>North, the North Guide and Nova do not provide medical diagnosis, treatment, rehabilitation, physiotherapy, nutrition therapy, mental-health care, emergency monitoring or individualized advice from a licensed clinician, certified trainer or other regulated professional. Content may be incomplete, generalized, generated from limited records or unsuitable for your circumstances.</p><p>Consult an appropriate qualified professional before beginning or changing exercise, particularly if you are pregnant, under 18, inactive, taking medication, recovering from illness or surgery, or have pain, injury, disability, cardiovascular, respiratory, metabolic, neurological or other health concerns.</p></section>
      <section><h2>3. Exercise safety</h2><p>Physical activity carries inherent risks, including soreness, falls, equipment failure, overexertion, dehydration, property damage, serious injury and death. Use suitable equipment and surroundings, inspect equipment, follow facility rules, learn proper technique, use a spotter where appropriate, choose conservative loads and progress gradually. Stop if you experience sharp or worsening pain, dizziness, faintness, numbness, loss of coordination, unusual shortness of breath or any alarming symptom.</p><p>Timers, targets, demonstrations, exercise substitutions, calorie estimates, progression ideas and recovery signals are aids only. They do not verify technique, equipment condition, readiness, safety or medical suitability.</p></section>
      <section id="legal-risk"><h2>4. Your decisions and assumption of risk</h2><p>You remain responsible for deciding whether, where and how to exercise; selecting appropriate movements, loads and intensity; supervising minors; obtaining medical clearance where appropriate; and seeking qualified help. To the fullest extent permitted by applicable law, you voluntarily assume the risks associated with your exercise decisions and use of information presented by North.</p><p>Do not use North while driving, operating machinery, or in any situation where looking at or interacting with a screen may create danger.</p></section>
      <section id="legal-ai"><h2>5. Nova, automated output and connected data</h2><p>Nova and other automated features can make mistakes, omit context or produce outdated, inconsistent or inappropriate output. Confidence labels and cited records do not guarantee accuracy. Review every suggestion before acting. North does not silently apply meaningful plan changes where approval is required, but your approval does not make a suggestion safe or professionally endorsed.</p><p>Health Connect, Samsung Health, browsers, devices and other third-party services determine what data they provide. Data may be delayed, duplicated, missing, estimated or measured differently. North summaries must not be used for diagnosis, emergency detection or clinical decisions.</p></section>
      <section><h2>6. Records, privacy and security</h2><p>You are responsible for the accuracy of information you enter and for protecting access to your account and devices. North attempts to preserve and synchronize records, but no storage or transmission method is guaranteed. Keep independent copies of records you cannot afford to lose. Do not enter information you are not authorized to store.</p><p>This notice is not a complete privacy policy or terms of service. A counsel-reviewed privacy policy, data-retention schedule and commercial terms are still required before broad public or paid use.</p></section>
      <section><h2>7. Third-party services and availability</h2><p>Links, integrations, app stores, browsers, health platforms and community content are operated or supplied by others. North does not control and is not responsible for their availability, accuracy, security, terms or conduct. Features may change, be interrupted or be withdrawn, and North is provided on an "as available" basis without a promise of uninterrupted or error-free operation.</p></section>
      <section><h2>8. Community and user content</h2><p>Community workouts and other member content are not verified as safe, accurate or suitable. Copying, saving or starting member content is your decision. You must have the rights and permissions needed for anything you upload, publish or share, and must not use North to infringe rights, harass others, distribute unlawful material or endanger another person.</p></section>
      <section id="legal-liability"><h2>9. Disclaimers and limitation of liability</h2><p>To the fullest extent permitted by applicable law, North and its operators, staff, contributors and service providers disclaim implied warranties, including fitness for a particular purpose, merchantability, accuracy and non-infringement. To that same extent, they will not be liable for indirect, incidental, special, consequential, exemplary or punitive damages, loss of data, lost profits, business interruption, personal injury or property damage arising from or related to North, Nova or other automated output, third-party content or your exercise decisions.</p><p>Nothing in this notice excludes or limits liability, warranties, consumer rights or other protections that cannot lawfully be excluded or limited. The enforceability of these terms depends on applicable law and the operator's jurisdiction.</p></section>
      <section><h2>10. Indemnity</h2><p>To the extent permitted by applicable law, you agree to be responsible for claims, losses and reasonable costs arising from your unlawful use of North, your infringement of another person's rights, content you publish, or your material breach of this notice. This provision does not apply where prohibited by law.</p></section>
      <section><h2>11. Minors</h2><p>North is not directed to children. A minor may use North only with the consent and active supervision of a parent or legal guardian and where permitted by law. Guardians are responsible for evaluating content, exercise choices and privacy implications.</p></section>
      <section><h2>12. Changes and severability</h2><p>North may update this notice as the product, operator or law changes. The effective date will be revised when material changes are published. If any provision is found unenforceable, the remaining provisions should continue to the extent allowed by law.</p></section>
      <section id="legal-contact"><h2>13. Questions and safety reports</h2><p>Questions about this notice or reports of unsafe content can be sent to <a href="mailto:hello@bodhix.io">hello@bodhix.io</a>. Use the in-app report tool for product defects. Do not use either channel for emergencies.</p></section>
    </div>
  </section>;
}
